# Generated by Django 3.2.4 on 2021-06-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='images/GitHub-Mark-Light-120px-plus.png', null=True, upload_to='images/'),
        ),
    ]
