# Generated by Django 3.2.4 on 2021-06-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_replies_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(default='images/logo1.png', null=True, upload_to='images/'),
        ),
    ]
