# Generated by Django 3.2.4 on 2021-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
