# Generated by Django 3.2.4 on 2021-06-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_events_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(auto_created=True, null=True),
        ),
    ]
