# Generated by Django 3.2.4 on 2021-06-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
