# Generated by Django 3.2.4 on 2021-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_thread_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, default='images/logo1.jpg', null=True, upload_to='images/'),
        ),
    ]
