# Generated by Django 3.2.4 on 2021-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_thread_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='links',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='thread',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
